### ISSUE TITLE
Fix confusing parameter names

### ISSUE THREAD

**Issue by abishekk92** [gumhq/sdk#3]
See https://github.com/gumhq/sdk/blob/b57a7483345929e0dccd13f4229e730086b93efa/packages/gpl-core/src/profile.ts#L37

The userAccount and user here refer to two different things. One proposed solution is to rename the `user` to `owner`

**Comment by vjgpt** [comment]
https://github.com/gumhq/sdk/commit/74b2f0a773abc1fe3c25b1c8f1ef4985bb3613c7
