### ISSUE TITLE
Fetch user/profile before attempting to create one.

### ISSUE THREAD

**Issue by abishekk92** [gumhq/sdk#7]
We should make it easy for developers to integrate in a manner that avoids surprises. Some of the common scenarios, I could think of are.

1. Creates a new user when they already have one
2. Creates a new profile when they already have one.

Since these are composable assets and could come from any application, we should make this distinction clear. We can accomplish this by adding the following functions.

# getOrCreateUser

This function should make a graphQL query, fetch the user based on their publickey and return the user or create a new user and then return it.

# getOrCreateProfile

Similar to the user, we should first fetch the profile based on the user before deciding to create a profile.

Once implemented these should become the primary way application developers use profile/users.

**Comment by vjgpt** [comment]
This is completed at c629b93be5a5ae74af1a0d7351af7ffe352a7de1.
