### ISSUE TITLE
Add a latency warning when using memcmp queries

### ISSUE THREAD

**Issue by abishekk92** [gumhq/sdk#8]
For example https://github.com/gumhq/sdk/blob/master/packages/gpl-core/src/post.ts#L19 would result in high latency if the underlying RPC is under heavy load or slow. We ideally want to discourage devs from using GPA and move them towards querying from the indexer.

**Comment by vjgpt** [comment]
This is completed 16cba070db5f07ec4d2324e9a5e111b5d8e8ae4f
